### ISSUE TITLE
Wallaby+jest doesn't work with babel 7

### ISSUE THREAD

**Issue by yurynix** [wix/yoshi#1079]
# 🐛 Bug Report

### 😯 Current Behavior
Wallaby's error in console:
```
Failed to run compilers on index.js, Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at api (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/@babel/plugin-syntax-object-rest-spread/lib/index.js:19:7)
    at /Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at /Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/amits/Documents/work/scheduler/statics/owner/owner-fes/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### 🤔 Expected Behavior
Not having an error, and wallaby actually working.

### 🔦 Context 

It makes me sad

### 💁 Possible Solution 

It seems that is caused because we force babel 6 in:
https://github.com/wix/yoshi/blob/master/packages/yoshi/config/wallaby-jest.js#L7

However jest, in `babel-preset-jest` using babel7 plugins -
https://github.com/facebook/jest/blob/master/packages/babel-preset-jest/index.js#L11

So we should lock `babel-preset-jest` version to before jest upgraded to babel 7, maybe:
`babel-preset-jest@23.2.0`

### 👣 Steps to Reproduce 

1. Clone `owner-fes` of `scheduler`
2. `npm install`
3. Open VSCode
4. Look at "Wallaby.js console"

### 💻 Code Sample

Private repo,  `owner-fes` of `scheduler`.

### 🌍 Your Environment

```
 System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.10.1 - ~/.nvm/versions/node/v8.11.3/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    Watchman: Not Found
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: Not Found
    Safari: 12.0.3
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  3.17.0 
    eslint-config-yoshi:  3.30.5 
    eslint-config-yoshi-base:  3.30.5 
    jest-environment-yoshi-bootstrap:  3.30.5 
    jest-environment-yoshi-puppeteer:  3.30.5 
    jest-yoshi-preset: ^3.24.1 => 3.30.5 
    storybook: Not Found
    tslint-config-yoshi:  3.30.5 
    tslint-config-yoshi-base:  3.30.5 
    typescript: ~3.0.1 => 3.0.3 
    webpack:  4.28.4 
    yoshi-config:  3.30.5 
    yoshi-helpers:  3.30.5 
    yoshi-runtime:  1.0.42 

 Zero config 🛴
```

**Comment by ronami** [comment]
I don't think this is the problem as Yoshi v3 is using Jest 23.6: https://github.com/facebook/jest/blob/v23.6.0/packages/babel-preset-jest/index.js#L12.

**Comment by yurynix** [comment]
It indeed uses `jest@23.6.0` and that's happening.
```
➜  owner-fes git:(master) ✗ npm ls jest
@wix/owner-fes@1.0.0 /Users/yurym/wix/scheduler/statics/owner/owner-fes
└─┬ yoshi@3.30.5
  └── jest@23.6.0 
```
