### ISSUE TITLE
__non_webpack_require__ is not defined

### ISSUE THREAD

**Issue by ariel7342** [wix/yoshi#1332]
# 🐛 Bug Report

### 😯 Current Behavior

when we try to run our project in srr mode we are getting this error :
```
{"stack":"ReferenceError: __non_webpack_require__ is not defined
at /Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/dist/test/mock/renderNativeComponent.js:11:9
at Array.forEach ()
at invalidateCache (/Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/dist/test/mock/renderNativeComponent.js:9:15)
at Object. (/Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/dist/test/mock/renderNativeComponent.js:21:13)
at step (/Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/node_modules/tslib/tslib.js:133:27)
at Object.next (/Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/node_modules/tslib/tslib.js:114:57)
at /Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/node_modules/tslib/tslib.js:107:75
at new Promise ()
at Object.__awaiter (/Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/node_modules/tslib/tslib.js:103:16)
at Object.renderNativeComponent (/Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/dist/test/mock/renderNativeComponent.js:16:20)","message":"__non_webpack_require__ is not defined"}
```

### 🤔 Expected Behavior

it should return the root page in ssr. working in youshi 3 , start getting this error when migrated to yoshi 4 

### 🔦 Context 

we have e2e test on ssr mode, they are failing now because of the error  

### 👣 Steps to Reproduce 

clone this - https://github.com/wix-private/ecom/tree/yoshi-4-migrate/client/wixstores-client/wixstores-client-product-page

`npm install`
`npm start`
go to `localhost:5000/ssr` 
should get the error 

### 💻 Code Sample

https://github.com/wix-private/ecom/tree/yoshi-4-migrate/client/wixstores-client/wixstores-client-product-page### 🌍 Your Environment

```
  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
    Yarn: Not Found
    npm: 6.9.0 - ~/.nvm/versions/node/v12.3.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: Not Found
    Firefox: 66.0.2
    Safari: 12.1
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  4.1.0 
    eslint-config-yoshi:  4.4.2 
    eslint-config-yoshi-base:  4.4.2 
    jest-environment-yoshi-bootstrap:  4.6.4 
    jest-environment-yoshi-puppeteer:  4.6.4 
    jest-yoshi-preset: ^4.6.4 => 4.6.4 
    storybook: Not Found
    tslint-config-yoshi:  3.30.5 
    tslint-config-yoshi-base:  3.30.5 
    typescript: ^3.4.3 => 3.4.5 
    webpack:  4.28.4 
    yoshi-config:  4.6.3 
    yoshi-helpers:  4.6.4 
    yoshi-runtime:  1.0.112 

 Yoshi config
{
  "servers": {
    "cdn": {
      "port": 5200
    }
  },
  "externals": {
    "react": {
      "amd": "react",
      "umd": "react",
      "commonjs": "react",
      "commonjs2": "react",
      "root": "React"
    },
    "react-dom": {
      "amd": "reactDOM",
      "umd": "react-dom",
      "commonjs": "react-dom",
      "commonjs2": "react-dom",
      "root": "ReactDOM"
    },
    "lodash": {
      "amd": "lodash",
      "commonjs": "lodash",
      "commonjs2": "lodash",
      "root": "_"
    }
  },
  "entry": {
    "editorMode": "./editorMode/editorMode.entry.tsx",
    "productPage": "./components/ProductPageApp/ProductPageApp.entry.ts",
    "productPageController": "./viewerScript/productPageController.ts",
    "worker": "./viewerScript/viewerScript.entry.ts",
    "mocks": "../test/mock/local-overrides/mocks.entry.ts"
  },
  "enhancedTpaStyle": true,
  "exports": "[name]",
  "umdNamedDefine": false,
  "hmr": true,
  "liveReload": false
}

```

**Comment by ranyitz** [comment]
`npm install` + `npm start` brings me the following error

![image](https://user-images.githubusercontent.com/11733036/58475706-60f02700-8157-11e9-9257-b343e9b68937.png)

**Comment by eranshabi** [comment]
you need to `npm run pretest`

**Comment by ranyitz** [comment]
Thanks @eranshabi 

@ariel7342 you are trying to use `__non_webpack_require__` in NodeJS environment, and you get `ReferenceError: __non_webpack_require__ is not defined` which makes perfect sense due to the fact that there is no Webpack running on your server code.

> it should return the root page in ssr. working in youshi 3 , start getting this error when migrated to yoshi 4

After looking at [the diff](https://github.com/wix-private/ecom/compare/master...yoshi-4-migrate#diff-c62a1689eea94b18c98ad4d2b3cf5cd6L144) it looks like you've used `experimentalServerBundle` feature. So you did use to have Webpack on the server. On yoshi@4 this feature is called [App Flow](https://wix.github.io/yoshi/docs/guides/app-flow#migration-for-fullstack-apps-bootstrap)

That's what you should do in order to move to use the app flow:

![image](https://user-images.githubusercontent.com/11733036/58477502-5dab6a00-815c-11e9-8b7b-3af579be86b0.png)

**Comment by ariel7342** [comment]
i change it as you said , but now i'm getting new error  
```
{"stack":"ReferenceError: document is not defined
at getCurrentScriptSource (webpack-internal:///../node_modules/yoshi/node_modules/webpack-dev-server/client/index.js:21:3)
at eval (webpack-internal:///../node_modules/yoshi/node_modules/webpack-dev-server/client/index.js:47:20)
at Object.../node_modules/yoshi/node_modules/webpack-dev-server/client/index.js (/Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/dist/statics/worker.bundle.js:2709:1)
at __webpack_require__ (/Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/dist/statics/worker.bundle.js:734:30)
at fn (/Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/dist/statics/worker.bundle.js:111:20)
at Object.3 (/Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/dist/statics/worker.bundle.js:2924:1)
at __webpack_require__ (/Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/dist/statics/worker.bundle.js:734:30)
at /Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/dist/statics/worker.bundle.js:801:37
at /Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/dist/statics/worker.bundle.js:804:10
at webpackUniversalModuleDefinition (/Users/ariell/Projects/ecom/client/wixstores-client/wixstores-client-product-page/dist/statics/worker.bundle.js:3:20)","message":"document is not defined"}
```

**Comment by ariel7342** [comment]
@deanshub we found the bug in the `hmr` , when we changed it to false in `package.json` the `/ssr` start working

**Comment by ranyitz** [comment]
@ariel7342 Good to hear that you've fixed it. Closing
