### ISSUE TITLE
Can't start with --production flag

### ISSUE THREAD

**Issue by vladik7244** [wix/yoshi#1444]
# 🐛 Bug Report

I am trying to locally run my server with `--production` flag
Build stuck at `Still waiting for app-server to start`

### 😯 Current Behavior
`target/server.log`:
/Users/vladyslavh/media-studio/node_modules/@wix/wnp-bootstrap-composer/lib/env-augmentor/env-validator.js:4
      throw new Error(`Mandatory env variable '${envKey}' is missing.`);
      ^

Error: Mandatory env variable 'GRPC_PORT' is missing.
    at forEach.envKey (/Users/vladyslavh/media-studio/node_modules/@wix/wnp-bootstrap-composer/lib/env-augmentor/env-validator.js:4:13)
    at Array.forEach (<anonymous>)
    at module.exports.env (/Users/vladyslavh/media-studio/node_modules/@wix/wnp-bootstrap-composer/lib/env-augmentor/env-validator.js:2:162)
    at Object.exports.validate (/Users/vladyslavh/media-studio/node_modules/@wix/wnp-bootstrap-composer/lib/env-augmentor/index.js:4:55)
    at InnerComposer.start (/Users/vladyslavh/media-studio/node_modules/@wix/wnp-bootstrap-composer/lib/composer.js:73:18)
    at BootstrapNg.start (/Users/vladyslavh/media-studio/node_modules/@wix/wnp-bootstrap-composer/index.js:48:27)
    at BootstrapNg.start (/Users/vladyslavh/media-studio/node_modules/wix-bootstrap-ng/index.js:17:18)
    at Object.<anonymous> (/Users/vladyslavh/media-studio/media-image-studio/index.js:20:4)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

### 👣 Steps to Reproduce 
close this repo: https://github.com/wix-private/media-studio
install modules 
cd media-image-studio
yarn start --production

### 🌍 Your Environment
  System:
    OS: macOS High Sierra 10.13.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: Not Found
  Browsers:
    Chrome: Not Found
    Firefox: 67.0.4
    Safari: 11.0.3
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi: Not Found
    eslint-config-yoshi: Not Found
    eslint-config-yoshi-base: Not Found
    jest-environment-yoshi-bootstrap: Not Found
    jest-environment-yoshi-puppeteer: Not Found
    jest-yoshi-preset: Not Found
    storybook: Not Found
    tslint-config-yoshi: Not Found
    tslint-config-yoshi-base: Not Found
    typescript: Not Found
    webpack: Not Found
    yoshi-config: Not Found
    yoshi-helpers: Not Found
    yoshi-runtime: Not Found

 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "react-intl": "ReactIntl",
    "prop-types": "PropTypes"
  },
  "servers": {
    "cdn": {
      "port": 3210
    }
  }
}

**Comment by ranyitz** [comment]
@vladik7244 I've been trying to reproduce the use-case:

`❯ g clone git@github.com:wix-private/media-studio.git`
`❯ cd media-studio`
`❯ yarn`
`❯ cd media-image-studio`
`❯ yarn start`

And I've got many errors

Like this, and more

![image](https://user-images.githubusercontent.com/11733036/60896263-b8150b80-a26e-11e9-9fb2-2f612a096c25.png)

Is there a simpler way to test this problem?

Can you create a minimal repro ([That's how](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff#how-to-create-a-minimal-reproduction))
