### ISSUE TITLE
running test:server tests is flaky plus mutates git tree

### ISSUE THREAD

**Issue by hugebdu** [wix/yoshi#1490]
running `npm run test:server` mutates many files (eg `package.json`, `.npmrc`) and also sometimes fails both on `before all` and `after all` steps:

```
  1) create-yoshi-app + yoshi e2e tests
       "before all" hook:
     Error: Command failed: /bin/sh -c npx lerna publish minor --yes --force-publish=* --no-git-tag-version --no-push --exact --dist-tag=latest --registry="http://localhost:4873"
      at makeError (/Users/daniels/sources/yoshi/node_modules/execa/index.js:174:9)
      at module.exports.sync (/Users/daniels/sources/yoshi/node_modules/execa/index.js:338:15)
      at handleShell (/Users/daniels/sources/yoshi/node_modules/execa/index.js:117:9)
      at Function.module.exports.shellSync (/Users/daniels/sources/yoshi/node_modules/execa/index.js:361:43)
      at publishMonorepo (/Users/daniels/sources/yoshi/scripts/utils/publishMonorepo.js:21:9)
      at Context.before (scripts/e2e.js:103:15)
```

```
  2) create-yoshi-app + yoshi e2e tests
       "after all" hook:
     TypeError: cleanup is not a function
      at Context.after (scripts/e2e.js:106:15)
```

**Comment by ronami** [comment]
We should explain it better in the docs: Template tests are full e2e tests that publish the entire Yoshi monorepo to fake the real user experience as much as we can. Those tests should normally only run in CI. We would like to be able to run a faster version of them locally: #759.

As for the flakyness, it should be better since #1480 was merged, is it still flaky for you?
