### ISSUE TITLE
Getting health check error on reload

### ISSUE THREAD

**Issue by astrauka** [wix/yoshi#188]
Getting health check error on reload, this makes the reload slower.

```
Thu, 13 Jul 2017 12:10:31 GMT wix:info:bootstrap-composer Listening on 33004                                       
ERRORS { FetchError: Timeout of 10000 ms with: request to http://localhost:33000/health/is_alive failed, reason: connect ECONNREFUSED 127.0.0.1:33000                                                                                  
    at ClientRequest.<anonymous> (/Users/.../node_modules/wix-bootstrap-testkit/node_modules/node-fetch/index.js:133:11)                                                                  
    at emitOne (events.js:96:13)                         
    at ClientRequest.emit (events.js:188:7)              
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)                         
    at Socket.emit (events.js:188:7)                     
    at emitErrorNT (net.js:1278:8)                       
    at _combinedTickCallback (internal/process/next_tick.js:74:11)                                                 
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)                                           
  name: 'FetchError',                                    
  message: 'Timeout of 10000 ms with: request to http://localhost:33000/health/is_alive failed, reason: connect ECONNREFUSED 127.0.0.1:33000',                                                                                         
  type: 'system',                                        
  errno: 'ECONNREFUSED',                                 
  code: 'ECONNREFUSED' } 
```

Steps to reproduce:

* start dev server
* update the `.js` file
* watch console for the error

Checked the url `127.0.0.1:33000` - it is returning the "Alive" response. Maybe the issue is that the server cannot server the response during reload?

**Comment by shlomitc** [comment]
Is this still happening? How can I reproduce it?

**Comment by astrauka** [comment]
You can reproduce it by stressing the CPUs such that after editing a JS file yoshi could not reload dev server in 10s. Once the timeout has been reached, you'll get the error.
Currently yoshi performance is improved and our app is able to reload in 8s, so I don't get the error.
