### ISSUE TITLE
Add --no-server for app-flow

### ISSUE THREAD

**Issue by davydof** [wix/yoshi#2208]
# 🙋 Feature Request

### 😯 Current Behavior
`yoshi start --no-server`

```
Error: Unknown or unexpected option: --no-server
    at Object.arg [as default] (/node_modules/arg/index.js:88:19)
    at start (/node_modules/yoshi-flow-app/build/scripts/start.js:17:31)
    at /node_modules/yoshi-flow-app/build/bin/yoshi-app.js:82:15 {
  code: 'ARG_UNKNOWN_OPTION'
}
```

### 🤔 Expected Behavior
`yoshi start --no-server`

1. If `dev/server.js` file doesn't exist do not throw the error:
```
```

Don't use the server in dev/server.js and don't open the localhost:3000

### 💁 Possible Solution 

...

### 🔦 Context 

...

**Comment by ranyitz** [comment]
Standalone apps needs a server to serve their initial `HTML`. When running on a platform and working on production it does makes sense to not bootstrap the server.

While what you suggested is a possible solution I would love to see how this is solved in `yoshi-editor-flow` which is specific flow for editor platform apps development. 

Can you please share a link to the repo you're working on and how to you work locally (if a server is not needed).

For now you can have a noop server (A server that doesn't do anything)

**Comment by davydof** [comment]
@ranyitz 
https://github.com/wix-private/accessibility-wizard
the flow is:
`yarn`
`yarn start`
open any editor with get parameter `&flowAppDefId=21953f88-1484-401d-bb16-1fb72bd2acdf`

**Comment by davydof** [comment]
@ranyitz
answered you in direct messages in slack because of privacy

**Comment by ranyitz** [comment]
> How I can use noop server
I just meant to use a small server that doesn't do anything as a workwround.

> I did try it and got errors from yoshi
What exactly did you try?

**Comment by yavorsky** [comment]
@davydof Hey. Thanks for creating an issue.
I have few questions to ask:

- If you are platform app, you still probably need settings panel? If yes, then having it serving locally via `3000/settings/app` with live reload could be useful?
- Can you please explain where are you using `client.bundle.js` ? If we are using `editorSDK` here, why it's not a part of editorScript?

Thanks

**Comment by davydof** [comment]
@ranyitz 
I've tried:
- remove `dev/server.js`
in this case I've got error:
```
Entry point is missing! Please create the entry point:
  - fullstack: index-dev.ts
  - client:    dev/server.ts
```

- use empty `dev/server.js`
with `BROWSER=none` it's good enough

**Comment by davydof** [comment]
@yavorsky 

> If you are platform app, you still probably need settings panel? If yes, then having it serving locally via 3000/settings/app with live reload could be useful?

I don't need the settings panel, so for us localhost:3000 is useless
we are the new side panel app, repo: https://github.com/wix-private/accessibility-wizard

> Can you please explain where are you using client.bundle.js ? If we are using editorSDK here, why it's not a part of editorScript?

here I open the sidePanel with my html in editor
https://github.com/wix-private/accessibility-wizard/blob/master/src/editor.ts#L9
https://github.com/wix-private/accessibility-wizard/blob/master/src/assets/side-panel.html
after use app.bundle.js from html file

so for local development I need only 3200 port with html file which using app.bundle.js

empty `dev/server.js` with `BROWSER=none` is enough to me
but I prefer to use it without `dev/server.js` at all and as I wrote in the first message:

> If dev/server.js file doesn't exist:
Don't throw the error.

And don't do anything(open localhost:3000, etc.)

**Comment by davydof** [comment]
@yavorsky @ranyitz 
friendly ping :)
guys please decide do we need some changes that I propose or we can leave it as it is

**Comment by ranyitz** [comment]
In general we would like to get to a place when editor platform apps are part of the `Editor Flow` so developing feature specific to platform apps for the `App Flow` does not makes a lot of sense. We could create an option for opting out, but it seems that you already have a workaround.

**Comment by davydof** [comment]
yes, I have workaround

**Comment by matveyok** [comment]
Why this is different than BIZ apps? I have biz app without server side, same use-case.
BTW +1 for this issue :) I (Wix Forms) wants it too.

**Comment by matveyok** [comment]
@ranyitz Following what you said about BIZ on slack, sometimes I already have biz project with app flow and I just need --no-server flag, migrating to biz flow is unnecessary and time consuming (maybe, didn't tried it with biz flow). Although in my case I'm in Yoshi 3 right now in the biz app so I'll probably migrate to biz flow anyway.
