### ISSUE TITLE
Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by tprupsys** [wix/yoshi#328]
I am getting the error below when running `yarn build` on https://github.com/wix-private/members-area/tree/master/members-area-app

It occurs randomly. `npm rebuild` seems to help. I am using yarn.

```
yarn build v0.24.6
$ yoshi build 
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tomasr/Development/members-area/members-area-app/node_modules/yoshi/plugins/node_modules/dtrace-provider/dtrace-provider.js:18:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
[12:12:38] Starting 'clean'...
```

**Comment by viliusl** [comment]
@tprupsys are you sure you are executing `npm build` always on same node version? Because it looks like native module and native modules are node-version-bound. So if you do `npm install` on one node version and then `npm build` on another these type of issues usually occur.

**Comment by viliusl** [comment]
even minor/patch node versions matter.

**Comment by viliusl** [comment]
@tprupsys also there is thread in https://github.com/yarnpkg/yarn/issues/1915 with dtrace-provider.

Might take a look @ it - suspects vary from offending trace version to multiple versions in node_modules.

**Comment by tprupsys** [comment]
@viliusl  I've just ran `rm yarn.lock && rm -rf node_modules && nvm install && yarn install && yarn start` - the same log was printed out. Maybe some global dependency affects it, dunno, didn't investigate. ;-)

Anyway, it does not fail or prevent me from working...

**Comment by viliusl** [comment]
Ok, please remind me of this on monday - will take a look as it seems annoying
