### ISSUE TITLE
Component Library Generator Fails

### ISSUE THREAD

**Issue by yairhaimo** [wix/yoshi#527]
# 🐛 Bug Report

### 😯 Current Behavior

After generating a component library project it fails, both javascript and typescript, with the following error:
```
info @storybook/react v4.0.0-alpha.16
info
exec: fatal: Not a git repository (or any of the parent directories): .git

exec: fatal: Not a git repository (or any of the parent directories): .git

/Users/yairh/temp/complib/node_modules/@storybook/core/dist/server/config/utils.js:73
    throw new Error('=> Create a storybook config file in "' + configDir + '/config.{ext}".');
    ^

Error: => Create a storybook config file in "./.storybook/config.{ext}".
    at getEntries (/Users/yairh/temp/complib/node_modules/@storybook/core/dist/server/config/utils.js:73:11)
    at exports.default (/Users/yairh/temp/complib/node_modules/@storybook/core/dist/server/config/webpack.config.js:58:40)
    at exports.default (/Users/yairh/temp/complib/node_modules/@storybook/core/dist/server/config.js:101:20)
    at exports.default (/Users/yairh/temp/complib/node_modules/@storybook/core/dist/server/middleware.js:19:37)
    at buildDev (/Users/yairh/temp/complib/node_modules/@storybook/core/dist/server/build-dev.js:167:36)
    at Object.<anonymous> (/Users/yairh/temp/complib/node_modules/@storybook/react/dist/server/index.js:11:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! complib@1.0.0 storybook: `start-storybook -p 6006`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the complib@1.0.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yairh/.npm/_logs/2018-08-23T11_52_02_289Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! complib@1.0.0 start: `yoshi start & npm run storybook`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the complib@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yairh/.npm/_logs/2018-08-23T11_52_02_336Z-debug.log
```

### 🤔 Expected Behavior

It should work 😊

### 👣 Steps to Reproduce 

1. `npx create-yoshi-app complib`
2. Choose component library
3. cd into directory and `npm start`

**Comment by yairhaimo** [comment]
Duplicate with https://github.com/wix/yoshi/issues/534

**Comment by yairhaimo** [comment]
@netanelgilad's solution will solve the `.git` issue.
Keeping this issue open for the `storybook` errors.

**Comment by ranyitz** [comment]
I couldn't reproduce this exact issue, but instead, after generating a new component library I see this, after running `npm start`:

![image](https://user-images.githubusercontent.com/11733036/46413667-23eba600-c72a-11e8-8767-ffe520183625.png)

**Comment by Schniz** [comment]
Seems like the problem is `@storybook/react@4` uses an `emotion` version that needs `react@16`: https://github.com/storybooks/storybook/issues/4191

I'll submit a PR that pins it to a working alpha (`14`) until we upgrade to React 16. wdyt?

cc @ehabshs @shlomitc

**Comment by ehabshs** [comment]
Seems good to me also ... Sorry for replying late
