### ISSUE TITLE
Creating a fullstack project with typescript doesn't work

### ISSUE THREAD

**Issue by henrykuzmick** [wix/yoshi#749]
# 🐛 Bug Report

### 😯 Current Behavior

When generating a new fullstack project with typescript, the generated project doesn't work.
server.log leaves this error:

```
2018-11-08T08:22:29.804Z wix:error:bootstrap-composer Unhandled Rejection at: Promise Promise {
  <rejected> { Error: Cannot find module '/Users/henrikask/Workspace/crash-nov-2018-store-6/src/server'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
      at Function.Module._load (internal/modules/cjs/loader.js:507:25)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:20:18)
      at /Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:206:16
      at Promise.all.appFns.map.appFn (/Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:175:25)
      at Array.map (<anonymous>)
      at composeExpressApp (/Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:174:29)
      at mainApps (/Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:137:19)
      at Promise.all.composerFns.map.composer (/Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:187:50)
      at Array.map (<anonymous>)
      at attachAndStart (/Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:187:34)
      at injectPlugins.then.then.appConfig (/Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:142:13) code: 'MODULE_NOT_FOUND' } } with Error: Cannot find module '/Users/henrikask/Workspace/crash-nov-2018-store-6/src/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:206:16
    at Promise.all.appFns.map.appFn (/Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:175:25)
    at Array.map (<anonymous>)
    at composeExpressApp (/Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:174:29)
    at mainApps (/Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:137:19)
    at Promise.all.composerFns.map.composer (/Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:187:50)
    at Array.map (<anonymous>)
    at attachAndStart (/Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:187:34)
    at injectPlugins.then.then.appConfig (/Users/henrikask/Workspace/crash-nov-2018-store-6/node_modules/wnp-bootstrap-composer/lib/composer.js:142:13)
```

**Comment by ranyitz** [comment]
That was an underlying problem with the node_platform, solved in https://github.com/wix-platform/wix-node-platform/pull/1787
