### ISSUE TITLE
create-yoshi-app universal type fails when stylable components (wix-style-react) is used

### ISSUE THREAD

**Issue by argshook** [wix/yoshi#982]
# 🐛 Bug Report

### 😯 Current Behavior

clean universal+typescript `create-yoshi-app` fails when using
components from wix-style-react

### 🤔 Expected Behavior

adding wix-style-react to universal app generated with `create-yoshi-app` should be trivial, no additional fixes

### 🔦 Context

many who use `create-yoshi-app` also use `wix-style-react`.
however, those who choose `universal` type, also need to do a fix.

### 💁 Possible Solution

fix is easy, but hard to find, it wastes some time.

`create-yoshi-app` should generate `index.js` with the following:

```diff
modified: my-generated-project/index.js
@@ -1,14 +1,16 @@
 const bootstrap = require('@wix/wix-bootstrap-ng');
 const { wixCssModulesRequireHook } = require('yoshi-runtime');
+const { attachHook } = require('@stylable/node');
 
 const rootDir = './dist/src';
 const getPath = path =>
   process.env.NODE_ENV === 'test' || process.env.DEBUGGER === 'true'
     ? `./src/${path}`
     : `${rootDir}/${path}`;
 
 wixCssModulesRequireHook();
+attachHook();
 
 bootstrap()
   .express(getPath('server'))
   .start({ disableCluster: process.env.NODE_ENV === 'development' });
```

this, however, would not be needed for those who don't use stylable.

so, the options are:
* add `attachHooks` for everyone always (easy fix, but maybe intrusive)
* improve `create-yoshi-app` interactive prompt to ask `would you like wix-style-react`, and add `attachHooks` only then (harder fix, but opt-in)

### 👣 Steps to Reproduce

```
npx create-yoshi-app
# choose universal
# choose typescript
npm install
npm install wix-style-react
```

put this code in `src/components/App/App.tsx`:

```js
import * as React from 'react';
import Text from 'wix-style-react/Text';
export default () => <Text>I should work!</Text>
```

observe `localhost:3000` failing to display `I should work!` text.  

<details>
<summary>
error from `target/server.log`
</summary>

```
2019-02-12T15:13:16.962Z wix:error:bootstrap-composer [requestId: 38fbce09-c208-4e6a-825c-9b967e7ba756] TypeError: (0 , _TextSt2.default) is not a function
    at Text (my-generated-project/node_modules/wix-style-react/dist/src/Text/Text.js:83:28)
    at my-generated-project/node_modules/react-dom/lib/ReactCompositeComponent.js:305:16
    at measureLifeCyclePerf (my-generated-project/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (my-generated-project/node_modules/react-dom/lib/ReactCompositeComponent.js:304:14)
    at ReactCompositeComponentWrapper._constructComponent (my-generated-project/node_modules/react-dom/lib/ReactCompositeComponent.js:279:21)
    at ReactCompositeComponentWrapper.mountComponent (my-generated-project/node_modules/react-dom/lib/ReactCompositeComponent.js:187:21)
    at Object.mountComponent (my-generated-project/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (my-generated-project/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (my-generated-project/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (my-generated-project/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (my-generated-project/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (my-generated-project/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (my-generated-project/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (my-generated-project/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (my-generated-project/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (my-generated-project/node_modules/react-dom/lib/ReactReconciler.js:45:35)
```

</details>

### 🌍 Your Environment

* yoshi@3.3.0
* wix-style-react@6.3.0

---

originally reported by @hitpopdimestop @bordi

**Comment by saarkuriel** [comment]
#884 - related to this
